import { FeatureGrid, PageHero, TextLink } from "@/components/primitives";

export const metadata = { title: "Breast Conservation Innovation" };

export default function Innovation() {
  return <>
    <PageHero number="03" eyebrow="Breast conservation innovation" title="Build technology around" italic="a real surgical need." intro="Clement’s clinician-led innovation platform asks how technology can help more suitable women preserve the breast, avoid unnecessary re-operation, understand their choices and recover with better quality of life."/>
    <FeatureGrid items={[{index:"01",title:"REBORN",text:"A digital patient education innovation designed to explain oncoplastic reconstruction and support clearer treatment conversations."},{index:"02",title:"Margin assessment",text:"Intra-operative technologies intended to identify cancer at the specimen edge and address re-excision after breast-conserving surgery."},{index:"03",title:"Surgical devices",text:"Low-thermal electrosurgical development focused on tissue effects in breast-conserving and oncoplastic surgery."}]}/>
    <section className="page-shell py-24"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[var(--coral)]">Industry collaboration areas</p><h2 className="serif mt-8 text-4xl leading-none tracking-[-.03em]">A translational test bed for breast conservation.</h2></div><div className="grid gap-5 sm:grid-cols-2">{["Intra-operative margin assessment","Imaging and surgical guidance","Low-thermal and tissue-preserving devices","Digital health and patient education","PROMs and outcome measurement","Clinical AI and decision support","Clinical implementation","Real-world validation pathways"].map((x,i)=><div key={x} className="flex min-h-40 flex-col justify-between border hairline p-6"><span className="text-xs text-[var(--coral)]">0{i+1}</span><h3 className="serif text-2xl">{x}</h3></div>)}</div></div></section>
    <section className="bg-[var(--ink)] py-24 text-white"><div className="page-shell grid gap-14 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow text-[var(--lime)]">Clinician-led translation</p><p className="muted-on-dark mt-6 max-w-sm text-[15px] leading-7">From unmet need and early validation to implementation in real clinical pathways.</p></div><div>{["Define a meaningful patient or workflow problem","Co-design with patients and multidisciplinary clinical teams","Generate the evidence appropriate to the technology and claim","Test usability, integration and implementation in context","Translate responsibly with academic, A*STAR and industry partners"].map((x,i)=><div key={x} className="grid grid-cols-[42px_1fr] border-t border-white/30 py-6"><span className="accent-on-dark text-xs font-bold">0{i+1}</span><p className="serif text-2xl leading-snug sm:text-3xl">{x}</p></div>)}</div></div></section>
    <section className="bg-[var(--lime)] py-24"><div className="page-shell grid gap-12 lg:grid-cols-[.55fr_1.45fr]"><div><p className="eyebrow">For medtech partners</p><p className="muted mt-6 text-[15px] leading-7">New tools must be evaluated for safety, usefulness, workflow fit and clinical value. Innovation does not guarantee improved outcomes.</p><div className="mt-9"><TextLink href="/contact">Collaborate on breast conservation innovation</TextLink></div></div><h2 className="serif max-w-5xl text-[clamp(2.7rem,6vw,6rem)] leading-[1.02] tracking-[-.04em]">Breast conservation is a platform for <i className="font-normal text-[var(--coral)]">clinically meaningful translation.</i></h2></div></section>
  </>;
}
